[Common]
;VLCLibPath=D:\Git\MarketPosCamera\VLC 
VLCLibPath=D:\Git\MarketPosCamera\Win32\Debug\VLC 

[Camera]
; Включено ли переопределение стандартных настроек камеры. 0 - выключено (по умолчанию), 
; 1 - включено
Override=0

Width=2560
Height=1440
Brightness=1
Contrast=1
Saturation=1
Hue=1

; коэффициент резкости
Sharpness=1 

; коэффициент экспозиции
Exposure=1
